const shortcuts = {
  "File Operations": [
    { title: "New Score",   description: "Create a new score",              shortkey1: "Ctrl",  shortkey2: "N",         shortkey3: "",  icon: null },
    { title: "Open",        description: "Open a score file",               shortkey1: "Ctrl",  shortkey2: "O",         shortkey3: "",  icon: "./Icons/Open.svg" },
    { title: "Save",        description: "Save the current score",          shortkey1: "Ctrl",  shortkey2: "S",         shortkey3: "",  icon: "./Icons/Save.svg" },
    { title: "Save As",     description: "Save score under a new name",     shortkey1: "Ctrl",  shortkey2: "Shift",     shortkey3: "S", icon: "./Icons/SaveAs.svg" },
    { title: "Close",       description: "Close the current score",         shortkey1: "Ctrl",  shortkey2: "W",         shortkey3: "",  icon: "./Icons/Close.svg" },
    { title: "Print",       description: "Print the score",                 shortkey1: "Ctrl",  shortkey2: "P",         shortkey3: "",  icon: "./Icons/Print.svg" },
    { title: "Quit",        description: "Quit MuseScore Studio",           shortkey1: "Ctrl",  shortkey2: "Q",         shortkey3: "",  icon: "./Icons/Exit.svg" },
  ],

  "General Editing": [
    { title: "Undo",                  description: "Undo the last action",                       shortkey1: "Ctrl",  shortkey2: "Z",         shortkey3: "",  icon: "./Icons/Undo.svg" },
    { title: "Redo",                  description: "Redo the last undone action",                shortkey1: "Ctrl",  shortkey2: "Shift",     shortkey3: "Z", icon: "./Icons/Redo.svg" },
    { title: "Copy",                  description: "Copy selected elements",                     shortkey1: "Ctrl",  shortkey2: "C",         shortkey3: "",  icon: "./Icons/Copy.svg" },
    { title: "Cut",                   description: "Cut selected elements",                      shortkey1: "Ctrl",  shortkey2: "X",         shortkey3: "",  icon: "./Icons/Cut.svg" },
    { title: "Paste",                 description: "Paste clipboard contents",                   shortkey1: "Ctrl",  shortkey2: "V",         shortkey3: "",  icon: "./Icons/Paste.svg" },
    { title: "Swap with Clipboard",   description: "Swap selection with clipboard contents",     shortkey1: "Ctrl",  shortkey2: "Shift",     shortkey3: "X", icon: null },
    { title: "Select All",            description: "Select all elements in the score",           shortkey1: "Ctrl",  shortkey2: "A",         shortkey3: "",  icon: "./Icons/SelectAll.svg" },
    { title: "Repeat Selection",      description: "Repeat the last copied selection",           shortkey1: "R",     shortkey2: "",          shortkey3: "",  icon: null },
    { title: "Delete",                description: "Clear selected notes/elements",              shortkey1: "Del",   shortkey2: "",          shortkey3: "",  icon: "./Icons/Delete.svg" },
    { title: "Delete Measures",       description: "Delete the selected measures entirely",      shortkey1: "Ctrl",  shortkey2: "Del",       shortkey3: "",  icon: null },
    { title: "Escape",                description: "Exit current mode or deselect",              shortkey1: "Esc",   shortkey2: "",          shortkey3: "",  icon: null },
    { title: "Edit Element",          description: "Enter edit mode for selected element",       shortkey1: "F2",    shortkey2: "",          shortkey3: "",  icon: null },
    { title: "Show/Hide Properties",  description: "Toggle the Properties panel",               shortkey1: "F8",    shortkey2: "",          shortkey3: "",  icon: null },
    { title: "Find / Go To",          description: "Jump to a specific bar number",             shortkey1: "Ctrl",  shortkey2: "F",         shortkey3: "",  icon: "./Icons/FindReplace.svg" },
    { title: "Reset Positions",       description: "Reset shapes and positions to default",     shortkey1: "Ctrl",  shortkey2: "R",         shortkey3: "",  icon: "./Icons/ResestPositions.svg" },
  ],

  "Note Input": [
    { title: "Toggle Note Input Mode",  description: "Enter or exit note input mode",                   shortkey1: "N",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Toggle Re-pitch Mode",    description: "Re-pitch existing notes without changing rhythm", shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "I", icon: null },
    { title: "Toggle Insert Mode",      description: "Insert notes without overwriting",               shortkey1: "Ctrl",  shortkey2: "I",     shortkey3: "", icon: null },
    { title: "Enter Rest",              description: "Input a rest at the current duration",            shortkey1: "0",     shortkey2: "",      shortkey3: "", icon: "./Icons/QuarterRest.svg" },
    { title: "Enter Note A",            description: "Input the note A",                               shortkey1: "A",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enter Note B",            description: "Input the note B",                               shortkey1: "B",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enter Note C",            description: "Input the note C",                               shortkey1: "C",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enter Note D",            description: "Input the note D",                               shortkey1: "D",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enter Note E",            description: "Input the note E",                               shortkey1: "E",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enter Note F",            description: "Input the note F",                               shortkey1: "F",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enter Note G",            description: "Input the note G",                               shortkey1: "G",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Add Note A to Chord",     description: "Add A to the current chord",                     shortkey1: "Shift", shortkey2: "A",     shortkey3: "", icon: null },
    { title: "Add Note B to Chord",     description: "Add B to the current chord",                     shortkey1: "Shift", shortkey2: "B",     shortkey3: "", icon: null },
    { title: "Add Note C to Chord",     description: "Add C to the current chord",                     shortkey1: "Shift", shortkey2: "C",     shortkey3: "", icon: null },
    { title: "Add Note D to Chord",     description: "Add D to the current chord",                     shortkey1: "Shift", shortkey2: "D",     shortkey3: "", icon: null },
    { title: "Add Note E to Chord",     description: "Add E to the current chord",                     shortkey1: "Shift", shortkey2: "E",     shortkey3: "", icon: null },
    { title: "Add Note F to Chord",     description: "Add F to the current chord",                     shortkey1: "Shift", shortkey2: "F",     shortkey3: "", icon: null },
    { title: "Add Note G to Chord",     description: "Add G to the current chord",                     shortkey1: "Shift", shortkey2: "G",     shortkey3: "", icon: null },
    { title: "Add Grace Note",          description: "Add an acciaccatura grace note",                 shortkey1: "/",     shortkey2: "",      shortkey3: "", icon: "./Icons/GraceNote.svg" },
    { title: "Add Tied Note",           description: "Tie the next note to the current one",           shortkey1: "T",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Toggle Duration Dot",     description: "Add or remove an augmentation dot",              shortkey1: ".",     shortkey2: "",      shortkey3: "", icon: "./Icons/AugmentationDot.svg" },
    { title: "Show/Hide Piano",         description: "Toggle the on-screen piano keyboard",            shortkey1: "P",     shortkey2: "",      shortkey3: "", icon: "./Icons/Piano.svg" },
  ],

  "Durations": [
    { title: "64th Note",                         description: "Set duration to 64th note",                           shortkey1: "1",     shortkey2: "",      shortkey3: "", icon: "./Icons/SixtyFourthNote.svg" },
    { title: "32nd Note",                         description: "Set duration to 32nd note",                           shortkey1: "2",     shortkey2: "",      shortkey3: "", icon: "./Icons/ThirtySecondNote.svg" },
    { title: "16th Note",                         description: "Set duration to 16th note",                           shortkey1: "3",     shortkey2: "",      shortkey3: "", icon: "./Icons/SixteenthNote.svg" },
    { title: "8th Note",                          description: "Set duration to 8th note",                            shortkey1: "4",     shortkey2: "",      shortkey3: "", icon: "./Icons/EighthNote.svg" },
    { title: "Quarter Note",                      description: "Set duration to quarter note",                        shortkey1: "5",     shortkey2: "",      shortkey3: "", icon: "./Icons/QuarterNote.svg" },
    { title: "Half Note",                         description: "Set duration to half note",                           shortkey1: "6",     shortkey2: "",      shortkey3: "", icon: "./Icons/HalfNote.svg" },
    { title: "Whole Note",                        description: "Set duration to whole note",                          shortkey1: "7",     shortkey2: "",      shortkey3: "", icon: "./Icons/WholeNote.svg" },
    { title: "Double Whole Note",                 description: "Set duration to double whole note (breve)",           shortkey1: "8",     shortkey2: "",      shortkey3: "", icon: "./Icons/DoubleWholeNote.svg" },
    { title: "Longa",                             description: "Set duration to longa",                               shortkey1: "9",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Halve Duration",                    description: "Halve the selected note's duration",                  shortkey1: "Q",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Double Duration",                   description: "Double the selected note's duration",                 shortkey1: "W",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Halve Duration (incl. dotted)",     description: "Halve duration, including dotted values",            shortkey1: "Shift", shortkey2: "Q",     shortkey3: "", icon: null },
    { title: "Double Duration (incl. dotted)",    description: "Double duration, including dotted values",           shortkey1: "Shift", shortkey2: "W",     shortkey3: "", icon: null },
    { title: "Paste Half Duration",               description: "Paste selection at half its original duration",       shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "Q", icon: null },
    { title: "Paste Double Duration",             description: "Paste selection at double its original duration",     shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "W", icon: null },
    { title: "Insert Full Measure Rest",          description: "Fill the selected measure with a full-measure rest",  shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "Del", icon: "./Icons/WholeRest.svg" },
  ],

  "Tuplets": [
    { title: "Duplet",      description: "Create a duplet tuplet",      shortkey1: "Ctrl",  shortkey2: "2",  shortkey3: "", icon: "./Icons/Duplet.svg" },
    { title: "Triplet",     description: "Create a triplet",            shortkey1: "Ctrl",  shortkey2: "3",  shortkey3: "", icon: "./Icons/Triplet.svg" },
    { title: "Quadruplet",  description: "Create a quadruplet tuplet",  shortkey1: "Ctrl",  shortkey2: "4",  shortkey3: "", icon: "./Icons/Quadruplet.svg" },
    { title: "Quintuplet",  description: "Create a quintuplet tuplet",  shortkey1: "Ctrl",  shortkey2: "5",  shortkey3: "", icon: "./Icons/Quintuplet.svg" },
    { title: "Sextuplet",   description: "Create a sextuplet tuplet",   shortkey1: "Ctrl",  shortkey2: "6",  shortkey3: "", icon: "./Icons/Sextuplet.svg" },
    { title: "Septuplet",   description: "Create a septuplet tuplet",   shortkey1: "Ctrl",  shortkey2: "7",  shortkey3: "", icon: "./Icons/Septuplet.svg" },
    { title: "Octuplet",    description: "Create an octuplet tuplet",   shortkey1: "Ctrl",  shortkey2: "8",  shortkey3: "", icon: "./Icons/Octuplet.svg" },
    { title: "Nonuplet",    description: "Create a nonuplet tuplet",    shortkey1: "Ctrl",  shortkey2: "9",  shortkey3: "", icon: "./Icons/Nonuplet.svg" },
  ],

  "Pitch & Transposition": [
    { title: "Pitch Up (semitone)",           description: "Move pitch up by a semitone",                        shortkey1: "Up",    shortkey2: "",      shortkey3: "", icon: null },
    { title: "Pitch Down (semitone)",         description: "Move pitch down by a semitone",                      shortkey1: "Down",  shortkey2: "",      shortkey3: "", icon: null },
    { title: "Pitch Up (octave)",             description: "Move pitch up by an octave",                         shortkey1: "Ctrl",  shortkey2: "Up",    shortkey3: "", icon: null },
    { title: "Pitch Down (octave)",           description: "Move pitch down by an octave",                       shortkey1: "Ctrl",  shortkey2: "Down",  shortkey3: "", icon: null },
    { title: "Pitch Up (diatonic)",           description: "Move pitch up by one diatonic step",                 shortkey1: "Alt",   shortkey2: "Shift", shortkey3: "Up", icon: null },
    { title: "Pitch Down (diatonic)",         description: "Move pitch down by one diatonic step",               shortkey1: "Alt",   shortkey2: "Shift", shortkey3: "Down", icon: null },
    { title: "Toggle Flat",                   description: "Add or remove a flat accidental",                    shortkey1: "-",     shortkey2: "",      shortkey3: "", icon: "./Icons/Flat.svg" },
    { title: "Toggle Natural",                description: "Add or remove a natural accidental",                 shortkey1: "=",     shortkey2: "",      shortkey3: "", icon: "./Icons/Natural.svg" },
    { title: "Toggle Sharp",                  description: "Add or remove a sharp accidental",                   shortkey1: "+",     shortkey2: "",      shortkey3: "", icon: "./Icons/Sharp.svg" },
    { title: "Enharmonic Spelling (both)",    description: "Change enharmonic spelling (concert & written)",     shortkey1: "J",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Enharmonic Spelling (current)", description: "Change enharmonic spelling (current pitch only)",    shortkey1: "Ctrl",  shortkey2: "J",     shortkey3: "", icon: null },
    { title: "Add Interval: Unison",          description: "Add a note a unison above",                          shortkey1: "Alt",   shortkey2: "1",     shortkey3: "", icon: null },
    { title: "Add Interval: 2nd",             description: "Add a note a 2nd above",                             shortkey1: "Alt",   shortkey2: "2",     shortkey3: "", icon: null },
    { title: "Add Interval: 3rd",             description: "Add a note a 3rd above",                             shortkey1: "Alt",   shortkey2: "3",     shortkey3: "", icon: null },
    { title: "Add Interval: 4th",             description: "Add a note a 4th above",                             shortkey1: "Alt",   shortkey2: "4",     shortkey3: "", icon: null },
    { title: "Add Interval: 5th",             description: "Add a note a 5th above",                             shortkey1: "Alt",   shortkey2: "5",     shortkey3: "", icon: null },
    { title: "Add Interval: 6th",             description: "Add a note a 6th above",                             shortkey1: "Alt",   shortkey2: "6",     shortkey3: "", icon: null },
    { title: "Add Interval: 7th",             description: "Add a note a 7th above",                             shortkey1: "Alt",   shortkey2: "7",     shortkey3: "", icon: null },
    { title: "Add Interval: Octave",          description: "Add a note an octave above",                         shortkey1: "Alt",   shortkey2: "8",     shortkey3: "", icon: null },
    { title: "Add Interval: 9th",             description: "Add a note a 9th above",                             shortkey1: "Alt",   shortkey2: "9",     shortkey3: "", icon: null },
  ],

  "Voices": [
    { title: "Voice 1",  description: "Assign selected notes to voice 1",  shortkey1: "Ctrl",  shortkey2: "Alt",  shortkey3: "1", icon: null },
    { title: "Voice 2",  description: "Assign selected notes to voice 2",  shortkey1: "Ctrl",  shortkey2: "Alt",  shortkey3: "2", icon: null },
    { title: "Voice 3",  description: "Assign selected notes to voice 3",  shortkey1: "Ctrl",  shortkey2: "Alt",  shortkey3: "3", icon: null },
    { title: "Voice 4",  description: "Assign selected notes to voice 4",  shortkey1: "Ctrl",  shortkey2: "Alt",  shortkey3: "4", icon: null },
  ],

  "Selection": [
    { title: "Next Chord",                    description: "Move selection to the next chord",                shortkey1: "Right",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Previous Chord",               description: "Move selection to the previous chord",            shortkey1: "Left",      shortkey2: "",      shortkey3: "", icon: null },
    { title: "Next Measure",                  description: "Jump selection to the next measure",              shortkey1: "Ctrl",      shortkey2: "Right", shortkey3: "", icon: null },
    { title: "Previous Measure",             description: "Jump selection to the previous measure",          shortkey1: "Ctrl",      shortkey2: "Left",  shortkey3: "", icon: null },
    { title: "Extend Selection Right",        description: "Add next note/rest to selection",                 shortkey1: "Shift",     shortkey2: "Right", shortkey3: "", icon: null },
    { title: "Extend Selection Left",         description: "Add previous note/rest to selection",             shortkey1: "Shift",     shortkey2: "Left",  shortkey3: "", icon: null },
    { title: "Extend Selection Up",           description: "Extend selection to staff above",                 shortkey1: "Shift",     shortkey2: "Up",    shortkey3: "", icon: null },
    { title: "Extend Selection Down",         description: "Extend selection to staff below",                 shortkey1: "Shift",     shortkey2: "Down",  shortkey3: "", icon: null },
    { title: "Select to End of Measure",      description: "Extend selection to end of measure",             shortkey1: "Ctrl",      shortkey2: "Shift", shortkey3: "Right", icon: null },
    { title: "Select to Start of Measure",    description: "Extend selection to start of measure",           shortkey1: "Ctrl",      shortkey2: "Shift", shortkey3: "Left", icon: null },
    { title: "Select to Start of Line",       description: "Extend selection to beginning of the line",      shortkey1: "Shift",     shortkey2: "Home",  shortkey3: "", icon: null },
    { title: "Select to End of Line",         description: "Extend selection to end of the line",            shortkey1: "Shift",     shortkey2: "End",   shortkey3: "", icon: null },
    { title: "Select to Start of Score",      description: "Extend selection to very beginning of score",    shortkey1: "Ctrl",      shortkey2: "Shift", shortkey3: "Home", icon: null },
    { title: "Select to End of Score",        description: "Extend selection to very end of score",          shortkey1: "Ctrl",      shortkey2: "Shift", shortkey3: "End", icon: null },
    { title: "Select Note Above",             description: "Select note/rest in staff above",                 shortkey1: "Alt",       shortkey2: "Up",    shortkey3: "", icon: null },
    { title: "Select Note Below",             description: "Select note/rest in staff below",                 shortkey1: "Alt",       shortkey2: "Down",  shortkey3: "", icon: null },
    { title: "Select Top Note in Chord",      description: "Move selection to top note of chord",            shortkey1: "Ctrl",      shortkey2: "Alt",   shortkey3: "Up", icon: null },
    { title: "Select Bottom Note in Chord",   description: "Move selection to bottom note of chord",         shortkey1: "Ctrl",      shortkey2: "Alt",   shortkey3: "Down", icon: null },
  ],

  "Page Navigation": [
    { title: "Go to First Element",   description: "Jump to the very first element in the score",    shortkey1: "Ctrl",  shortkey2: "Home",  shortkey3: "", icon: null },
    { title: "Go to Last Element",    description: "Jump to the very last element in the score",     shortkey1: "Ctrl",  shortkey2: "End",   shortkey3: "", icon: null },
    { title: "Next Screen",           description: "Scroll forward one screen",                      shortkey1: "PgUp",  shortkey2: "",      shortkey3: "", icon: null },
    { title: "Previous Screen",       description: "Scroll back one screen",                         shortkey1: "PgDn",  shortkey2: "",      shortkey3: "", icon: null },
    { title: "Next Page",             description: "Jump to the next page",                          shortkey1: "Ctrl",  shortkey2: "PgUp",  shortkey3: "", icon: null },
    { title: "Previous Page",         description: "Jump to the previous page",                      shortkey1: "Ctrl",  shortkey2: "PgDn",  shortkey3: "", icon: null },
    { title: "Zoom In",               description: "Increase zoom level",                            shortkey1: "Ctrl",  shortkey2: "=",     shortkey3: "", icon: null },
    { title: "Zoom Out",              description: "Decrease zoom level",                            shortkey1: "Ctrl",  shortkey2: "-",     shortkey3: "", icon: null },
    { title: "Zoom to 100%",          description: "Reset zoom to 100%",                             shortkey1: "Ctrl",  shortkey2: "0",     shortkey3: "", icon: null },
    { title: "Show/Hide Timeline",    description: "Toggle the timeline panel",                      shortkey1: "F12",   shortkey2: "",      shortkey3: "", icon: null },
    { title: "Full Screen",           description: "Toggle full screen mode",                        shortkey1: "F11",   shortkey2: "",      shortkey3: "", icon: null },
  ],

  "Score Elements & Notation": [
    { title: "Add Slur",                      description: "Add a slur over the selection",                   shortkey1: "S",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Articulation: Accent",          description: "Add an accent articulation",                      shortkey1: "Shift", shortkey2: "V",     shortkey3: "", icon: "./Icons/Accent.svg" },
    { title: "Articulation: Marcato",         description: "Add a marcato articulation",                      shortkey1: "Shift", shortkey2: "O",     shortkey3: "", icon: "./Icons/Marcato.svg" },
    { title: "Articulation: Staccato",        description: "Add a staccato articulation",                     shortkey1: "Shift", shortkey2: "S",     shortkey3: "", icon: "./Icons/Staccato.svg" },
    { title: "Articulation: Tenuto",          description: "Add a tenuto articulation",                       shortkey1: "Shift", shortkey2: "N",     shortkey3: "", icon: "./Icons/Tenuto.svg" },
    { title: "Hairpin: Crescendo",            description: "Add a crescendo hairpin",                         shortkey1: "<",     shortkey2: "",      shortkey3: "", icon: "./Icons/Crescendo.svg" },
    { title: "Hairpin: Decrescendo",          description: "Add a decrescendo hairpin",                       shortkey1: ">",     shortkey2: "",      shortkey3: "", icon: "./Icons/Decrescendo.svg" },
    { title: "Flip Direction",                description: "Flip stem, slur, or tie direction",               shortkey1: "X",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Mirror Notehead",               description: "Mirror the notehead to the other side of stem",   shortkey1: "Shift", shortkey2: "X",     shortkey3: "", icon: null },
    { title: "Add Parentheses",               description: "Add parentheses around selected element",         shortkey1: "(",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Toggle Visibility",             description: "Show or hide the selected element",               shortkey1: "V",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Toggle Multimeasure Rest",      description: "Toggle multimeasure rest consolidation",          shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "M", icon: "./Icons/MultimeasureRest.svg" },
    { title: "Move to Staff Above",           description: "Move selected note/rest to the staff above",      shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "Up", icon: null },
    { title: "Move to Staff Below",           description: "Move selected note/rest to the staff below",      shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "Down", icon: null },
  ],

  "Text": [
    { title: "Add Staff Text",        description: "Insert a staff text element",                shortkey1: "Ctrl",  shortkey2: "T",     shortkey3: "", icon: null },
    { title: "Add System Text",       description: "Insert a system-wide text element",          shortkey1: "Ctrl",  shortkey2: "Shift", shortkey3: "T", icon: null },
    { title: "Add Dynamic",           description: "Insert a dynamic marking (p, f, etc.)",      shortkey1: "Ctrl",  shortkey2: "D",     shortkey3: "", icon: null },
    { title: "Add Expression Text",   description: "Insert an expression text marking",          shortkey1: "Ctrl",  shortkey2: "E",     shortkey3: "", icon: null },
    { title: "Add Rehearsal Mark",    description: "Insert a rehearsal mark",                    shortkey1: "Ctrl",  shortkey2: "M",     shortkey3: "", icon: null },
    { title: "Add Tempo Marking",     description: "Insert a tempo marking",                     shortkey1: "Alt",   shortkey2: "Shift", shortkey3: "T", icon: "./Icons/TempoMark.svg" },
    { title: "Add Lyrics",            description: "Start entering lyrics below the staff",      shortkey1: "Ctrl",  shortkey2: "L",     shortkey3: "", icon: null },
    { title: "Lyrics: Next Syllable", description: "Move to the next syllable in lyrics mode",   shortkey1: "Space", shortkey2: "",      shortkey3: "", icon: null },
    { title: "Lyrics: Prev Syllable", description: "Move to the previous syllable",              shortkey1: "Shift", shortkey2: "Space", shortkey3: "", icon: null },
    { title: "Lyrics: Hyphen",        description: "Insert a lyric hyphen between syllables",    shortkey1: "-",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Lyrics: Melisma",       description: "Extend a lyric syllable across notes",       shortkey1: "_",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Add Lyric Verse",       description: "Add a new lyric verse below",                shortkey1: "Return",shortkey2: "",      shortkey3: "", icon: null },
    { title: "Add Chord Symbol",      description: "Insert a chord symbol (e.g. Dm7)",           shortkey1: "Ctrl",  shortkey2: "K",     shortkey3: "", icon: null },
    { title: "Add Figured Bass",      description: "Insert figured bass notation",               shortkey1: "Ctrl",  shortkey2: "G",     shortkey3: "", icon: null },
    { title: "Special Characters",    description: "Open the special characters dialog",         shortkey1: "Shift", shortkey2: "F2",    shortkey3: "", icon: null },
    { title: "Bold",                  description: "Toggle bold formatting on text",             shortkey1: "Ctrl",  shortkey2: "B",     shortkey3: "", icon: "./Icons/Bold.svg" },
    { title: "Italic",                description: "Toggle italic formatting on text",           shortkey1: "Ctrl",  shortkey2: "I",     shortkey3: "", icon: "./Icons/Italic.svg" },
    { title: "Underline",             description: "Toggle underline formatting on text",        shortkey1: "Ctrl",  shortkey2: "U",     shortkey3: "", icon: "./Icons/Underline.svg" },
  ],

  "Layout & Formatting": [
    { title: "Insert Measure Before",         description: "Insert one measure before the selection",             shortkey1: "Ins",   shortkey2: "",      shortkey3: "", icon: null },
    { title: "Insert Multiple Measures",      description: "Insert multiple measures before the selection",       shortkey1: "Ctrl",  shortkey2: "Ins",   shortkey3: "", icon: null },
    { title: "Append Measure",                description: "Append one measure at the end of the score",          shortkey1: "Ctrl",  shortkey2: "B",     shortkey3: "", icon: null },
    { title: "Append Multiple Measures",      description: "Append multiple measures at the end of the score",   shortkey1: "Alt",   shortkey2: "Shift", shortkey3: "B", icon: null },
    { title: "Add/Remove System Break",       description: "Toggle a system break at the selected barline",      shortkey1: "Return",shortkey2: "",      shortkey3: "", icon: null },
    { title: "Add/Remove Page Break",         description: "Toggle a page break at the selected barline",        shortkey1: "Ctrl",  shortkey2: "Return",shortkey3: "", icon: null },
    { title: "Increase Layout Stretch",       description: "Stretch the selected measures wider",                 shortkey1: "}",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Decrease Layout Stretch",       description: "Compress the selected measures narrower",            shortkey1: "{",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Add/Remove Instruments",        description: "Open the instruments/staves panel",                  shortkey1: "I",     shortkey2: "",      shortkey3: "", icon: null },
    { title: "Open Instruments Dialog",       description: "Open the full instruments dialog",                    shortkey1: "F7",    shortkey2: "",      shortkey3: "", icon: null },
  ],

  "Playback & UI": [
    { title: "Play / Stop",           description: "Start or stop score playback",               shortkey1: "Space", shortkey2: "",      shortkey3: "", icon: null },
    { title: "Show/Hide Mixer",       description: "Toggle the Mixer panel",                     shortkey1: "F10",   shortkey2: "",      shortkey3: "", icon: null },
    { title: "Show/Hide Palettes",    description: "Toggle the Palettes panel",                  shortkey1: "F9",    shortkey2: "",      shortkey3: "", icon: null },
    { title: "Search Palettes",       description: "Search within the Palettes panel",           shortkey1: "Ctrl",  shortkey2: "F9",    shortkey3: "", icon: null },
    { title: "Open Master Palette",   description: "Open the Master Palette dialog",             shortkey1: "Shift", shortkey2: "F9",    shortkey3: "", icon: null },
    { title: "Next UI Pane",          description: "Move focus to the next UI pane or window",   shortkey1: "F6",    shortkey2: "",      shortkey3: "", icon: null },
    { title: "Previous UI Pane",      description: "Move focus to the previous UI pane",         shortkey1: "Shift", shortkey2: "F6",    shortkey3: "", icon: null },
  ],
};
